openapi: 3.0.3
info:
  title: Best Protocol
  description: API Interface and Model for Best Protocol
  version: 1.0.0
  contact:
    email: csabavadasz79@gmail.com
servers:
  - url: 'http://localhost:8080'
tags:
  - name: government-agency
  - name: government-representative
  - name: address
  - name: contact
  - name: user

paths:
  /api/admin/government-representatives:
    post:
      tags:
        - government-representative
      summary: Add a new Government Representative
      description: Add a new Government Representative to the database
      operationId: addNewGovernmentRepresentative
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewGovernmentRepresentativeModel'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Government Representative not found
        '405':
          description: Validation exception
    get:
      tags:
        - government-representative
      summary: Render all Government Representatives
      description: Render all Government Representatives from the database
      operationId: renderAllGovernmentRepresentatives
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GovernmentRepresentativeModel'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Government Representative not found
        '405':
          description: Validation exception

  /api/admin/government-representatives/{governmentRepresentativeId}:
    get:
      tags:
        - government-representative
      summary: Find Government Representative by ID
      description: Returns a single Government Representative
      operationId: getGovernmentRepresentativeById
      parameters:
        - name: governmentRepresentativeId
          in: path
          description: ID of Government Representative to return
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovernmentRepresentativeModel'
        '400':
          description: Invalid ID supplied
        '404':
          description: Government Representative not found
    put:
      tags:
        - government-representative
      summary: Update an existing Government Representative
      description: Update an existing Government Representative by Id
      operationId: updateGovernmentAgency
      parameters:
        - name: governmentRepresentativeId
          in: path
          description: ID of Government Representative to return
          required: true
          schema:
            format: uuid
            type: string
      requestBody:
        description: Update an existing Government Representative
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifiedGovernmentRepresentativeModel'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovernmentRepresentativeModel'
        '400':
          description: Invalid ID supplied
        '404':
          description: Government Representative not found
        '405':
          description: Validation exception
    delete:
      tags:
        - government-representative
      summary: Delete a Government Representative
      description: Delete a Government Representative
      operationId: deleteGovernmentRepresentative
      parameters:
        - name: governmentRepresentativeId
          in: path
          description: ID of Government Representative to return
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '204':
          description: successful operation

  /api/admin/government-agencies:
    post:
      tags:
        - government-agency
      summary: Add a new Government Agency
      description: Add a new Government Agency to the database
      operationId: addNewGovernmentAgency
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewGovernmentAgencyModel'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Government Agency not found
        '405':
          description: Validation exception
    get:
      tags:
        - government-agency
      summary: Render all Government Agencies
      description: Render all Government Agencies from the database
      operationId: renderAllGovernmentAgencies
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GovernmentAgencyModel'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Government Agency not found
        '405':
          description: Validation exception

  /api/admin/government-agencies/{governmentAgencyId}:
    get:
      tags:
        - government-agency
      summary: Find Government Agency by ID
      description: Returns a single Government Agency
      operationId: getGovernmentAgencyById
      parameters:
        - name: governmentAgencyId
          in: path
          description: ID of Government Agency to return
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovernmentAgencyModel'
        '400':
          description: Invalid ID supplied
        '404':
          description: Government Agency not found
    put:
      tags:
        - government-agency
      summary: Update an existing Government Agency
      description: Update an existing Government Agency by Id
      operationId: updateGovernmentAgency
      parameters:
        - name: governmentAgencyId
          in: path
          description: ID of Government Agency to return
          required: true
          schema:
            format: uuid
            type: string
      requestBody:
        description: Update an existing Government Agency
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifiedGovernmentAgencyModel'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovernmentAgencyModel'
        '400':
          description: Invalid ID supplied
        '404':
          description: Government Agency not found
        '405':
          description: Validation exception
    delete:
      tags:
        - government-agency
      summary: Delete a Government Agency
      description: Delete a Government Agency
      operationId: deleteGovernmentAgency
      parameters:
        - name: governmentAgencyId
          in: path
          description: ID of Government Agency to return
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '204':
          description: successful operation

components:
  schemas:
    NewGovernmentRepresentativeModel:
      type: object
      properties:
        prefix:
          description: Prefix of the name of the Government Representative
          type: string
          example: 'dr.'
        firstName:
          description: First name of the Government Representative
          type: string
          example: 'Csaba'
        midName:
          description: Mid name of the Government Representative
          type: string
          example: 'Optional'
        lastName:
          description: Last name of the Government Representative
          type: string
          example: 'Vadász'
        suffix:
          description: Suffix of the name of the Government Representative
          type: string
          example: 'PhD'
        isMale:
          description: Gender of the Representatives
          type: boolean
          example: true
        jobTitle:
          description: Job title of the Government Representative
          type: string
          example: "Miniszterelnökséget vezető miniszter"
        note:
          description: Any extra, useful information
          type: string
          example: 'Keresztneve: Dóra, ételérzékenység: nincs, egyéb: vegán'
        image:
          description: Photo of the Government Representative
          type: string
          format: binary

    GovernmentRepresentativeModel:
      type: object
      properties:
        id:
          description: Id of the Government Representative
          type: string
          format: uuid
          example: '3a8ea9f1-1a95-4caf-932f-2f988052933b'
        createdAt:
          description: Creation time of Government Representative entity
          type: string
          format: timestamp
          example: '2019-01-21T05:47:08.644'
        updatedAt:
          description: Updated time of Government Representative entity
          type: string
          format: timestamp
          example: '2019-01-21T05:47:08.644'
        createdBy:
          description: User id who created the Government Representative entity
          type: string
          format: uuid
          example: '3a8ea9f1-1a95-4caf-932f-2f988052933b'
        updatedBy:
          description: User id who updated the Government Representative entity
          type: string
          format: uuid
          example: '3a8ea9f1-1a95-4caf-932f-2f988052933b'
        prefix:
          description: Prefix of the name of the Government Representative
          type: string
          example: 'dr.'
        firstName:
          description: First name of the Government Representative
          type: string
          example: 'Csaba'
        midName:
          description: Mid name of the Government Representative
          type: string
          example: 'Optional'
        lastName:
          description: Last name of the Government Representative
          type: string
          example: 'Vadász'
        suffix:
          description: Suffix of the name of the Government Representative
          type: string
          example: 'PhD'
        isMale:
          description: Gender of the Representatives
          type: boolean
          example: true
        jobTitle:
          description: Job title of the Government Representative
          type: string
          example: "Miniszterelnökséget vezető miniszter"
        note:
          description: Any extra, useful information
          type: string
          example: 'Keresztneve: Dóra, ételérzékenység: nincs, egyéb: vegán'
        image:
          description: Photo of the Government Representative
          type: string
          format: binary
        availability:
          $ref: '#/components/schemas/Availability'

    ModifiedGovernmentRepresentativeModel:
      type: object
      properties:
        prefix:
          description: Prefix of the name of the Government Representative
          type: string
          example: 'dr.'
        firstName:
          description: First name of the Government Representative
          type: string
          example: 'Csaba'
        midName:
          description: Mid name of the Government Representative
          type: string
          example: 'Optional'
        lastName:
          description: Last name of the Government Representative
          type: string
          example: 'Vadász'
        suffix:
          description: Suffix of the name of the Government Representative
          type: string
          example: 'PhD'
        isMale:
          description: Gender of the Representatives
          type: boolean
          example: true
        jobTitle:
          description: Job title of the Government Representative
          type: string
          example: "Miniszterelnökséget vezető miniszter"
        note:
          description: Any extra, useful information
          type: string
          example: 'Keresztneve: Dóra, ételérzékenység: nincs, egyéb: vegán'
        image:
          description: Photo of the Government Representative
          type: string
          format: binary
        availability:
          $ref: '#/components/schemas/Availability'

    NewGovernmentModel:
      type: object
      properties:
        name:
          description: Name of the Government
          type: string
          example: 'Belügyminisztérium'
        nameSecretariat:
          description: Name of the Secretariat
          type: string
          example: 'Szociális ügyekért felelős államtitkárság'
        note:
          description: Any extra, useful information
          type: string
          example: 'Szociális ügyekért felelős államtitkárság'

    GovernmentModel:
      type: object
      properties:
        id:
          description: Id of the Government
          type: string
          format: uuid
          example: '3a8ea9f1-1a95-4caf-932f-2f988052933b'
        createdAt:
          description: Creation time of Government entity
          type: string
          format: timestamp
          example: '2019-01-21T05:47:08.644'
        updatedAt:
          description: Updated time of Government entity
          type: string
          format: timestamp
          example: '2019-01-21T05:47:08.644'
        createdBy:
          description: User id who created the Government entity
          type: string
          format: uuid
          example: '3a8ea9f1-1a95-4caf-932f-2f988052933b'
        updatedBy:
          description: User id who updated the Government entity
          type: string
          format: uuid
          example: '3a8ea9f1-1a95-4caf-932f-2f988052933b'
        name:
          description: Name of the Government
          type: string
          example: 'Belügyminisztérium'
        nameSecretariat:
          description: Name of the Secretariat
          type: string
          example: 'Szociális ügyekért felelős államtitkárság'
        note:
          description: Any extra, useful information
          type: string
          example: 'Szociális ügyekért felelős államtitkárság'
        availability:
          $ref: '#/components/schemas/Availability'

    ModifiedGovernmentModel:
      type: object
      properties:
        name:
          description: Name of the Government
          type: string
          example: 'Belügyminisztérium'
        nameSecretariat:
          description: Name of the Secretariat
          type: string
          example: 'Szociális ügyekért felelős államtitkárság'
        note:
          description: Any extra, useful information
          type: string
          example: 'Szociális ügyekért felelős államtitkárság'
        availability:
          $ref: '#/components/schemas/Availability'

    Availability:
      type: string
      enum:
        - AVAILABLE
        - ARCHIVE
        - DELETED
